# Generated by Django 6.0.3 on 2026-05-14 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_alter_company_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('email', 'user'), name='unique_email_user'),
        ),
    ]
